
DEEPSEEK_API_KEY = "sk-81bcdb6a98134db8aba35b712809db1f"

QWEN_API_KEY = "sk-d527183d4a71482a81a9c75620f4e66c"

MITA_API_KEY="mk-3549332B919E20FAD6C3E59E77D01CD6"

KIMI_API_KEY="sk-xWfHugUIP1VEHVm3emuuHbb99TGarSKw1Pl1EhhPOvoHdds5"


